pipeline:
  build-and-push:
    image: plugins/docker
    repo: phpdrone/ghcli
    tags:
      - ${DRONE_BRANCH##*/}-${DRONE_TAG=latest}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      branch: [ master ]
